### ISSUE TITLE
SMTP email 

### ISSUE THREAD

**Issue by snoopyxz** [nixrajput/social-media-api-nodejs#6]
hello,  I don't know why I'm not receiving email with otp, could you tell me how to configure the stmp in config.env

![imagem](https://user-images.githubusercontent.com/104867141/190036839-d6c8d4ec-cc69-4b33-8a1e-e42edb62c12f.png)

**Comment by nixrajput** [comment]
Have you added the correct SENDGRID_API_KEY in the `config.env` file ??

**Comment by snoopyxz** [comment]
no.

**Comment by nixrajput** [comment]
don't use Gmail

Edit `SMTP_FROM = 'starlight <starlight@xyz.com>'`

you can use any domain at the place of `xyz`

**Comment by snoopyxz** [comment]
Thanks for help its working. Big thanks 🚀🚀

**Comment by snoopyxz** [comment]
Im having another problem when i post something i got this error

**Comment by snoopyxz** [comment]
![Screenshot_20220914-101550_Rippl!](https://user-images.githubusercontent.com/104867141/190114488-9cf0afc4-f2fb-4cb0-aa48-89acdb455411.png)

**Comment by snoopyxz** [comment]
public id is required
