### ISSUE TITLE
public id is required

### ISSUE THREAD

**Issue by snoopyxz** [nixrajput/social-media-api-nodejs#7]
![190114488-9cf0afc4-f2fb-4cb0-aa48-89acdb455411](https://user-images.githubusercontent.com/104867141/190237493-a732c2b8-fdd3-4f75-9e27-c3c5fecb6049.png)

**Comment by snoopyxz** [comment]
{
    "caption": "hi.",
    "mediaFiles": [
        {
            "public_id": null,
            "url": null,
            "mediaType": "image"
        }
    ]
}

**Comment by snoopyxz** [comment]
can u help me with this error ?

**Comment by snoopyxz** [comment]
![imagem](https://user-images.githubusercontent.com/104867141/190238926-d2c8f685-e64c-46e5-b4f2-f06830c2cc96.png)

**Comment by nixrajput** [comment]
you have to provide `publicId` and `url` for an image that you will get from cloudinary upload.

**Comment by snoopyxz** [comment]
Who i do That i dont understand

**Comment by snoopyxz** [comment]
I dont know how to do that can u explain me step by step in detail

**Comment by nixrajput** [comment]
When you upload an image or a video to cloudinary, you get `publicId` and `url` in response.
 
But in the case of this application, that has been taken care of in the code.

**Comment by snoopyxz** [comment]
i dont understand i dont get any publicId or url in response

**Comment by snoopyxz** [comment]
when i try upload something i get the error public id required

**Comment by snoopyxz** [comment]
4 real i don't understand anything i have to do to stop getting this error

**Comment by nixrajput** [comment]
how are u uploading to cloudinary...show me

**Comment by snoopyxz** [comment]
1 sec

**Comment by snoopyxz** [comment]
https://anonfiles.com/S117258cy7/screen-20220917-192550_mp4

**Comment by nixrajput** [comment]
I want to know which endpoint u are using to upload the video.

**Comment by snoopyxz** [comment]
https://anonfiles.com/A6482684ya/Cloudinary_Management_Console_-_Settings_Mozilla_Firefox_2022-09-18_00-04-35_mp4

**Comment by snoopyxz** [comment]
this ?

**Comment by nixrajput** [comment]
I think this is a video file link, isn't it?

**Comment by snoopyxz** [comment]
yes

**Comment by snoopyxz** [comment]
what is a "endpoint"

**Comment by nixrajput** [comment]
ok

First, u have to upload this video file into cloudinary, then u will get publicId and URL in response.

Use Cloudinary plugin or official endpoint to upload.

I think it will clear your doubt.

**Comment by nixrajput** [comment]
How much experience do you have in programming and which programming language?

**Comment by snoopyxz** [comment]
![Uploading imagem.png…]()

**Comment by snoopyxz** [comment]
![imagem](https://user-images.githubusercontent.com/104867141/190879287-8522eb52-fcf6-4bdf-a736-fb3b4a3fb0ca.png)

**Comment by nixrajput** [comment]
For example:-
In the second image,

publicId - `cld-sample-5`
URL - right click on image and copy URL

**Comment by snoopyxz** [comment]
and now what i do it that ?

**Comment by snoopyxz** [comment]
can we do teamviewer tomorrow please ? :(

**Comment by snoopyxz** [comment]
i send you message on instagram

**Comment by nixrajput** [comment]
we can do it now, bcz i will be busy tomorrow.

**Comment by snoopyxz** [comment]
ok 1 sec

**Comment by snoopyxz** [comment]
ID: 1 056 554 892

password: z9f7pqwp

**Comment by nixrajput** [comment]
wait...

**Comment by snoopyxz** [comment]
ok np.

**Comment by nixrajput** [comment]
u got it??

**Comment by snoopyxz** [comment]
if i want to upload do i have to do this every time?

**Comment by nixrajput** [comment]
u can do it by code itself, that is how I am doing in my app

**Comment by snoopyxz** [comment]
hm ok in the future you will later make it available to everyone here on github?

**Comment by nixrajput** [comment]
sure

**Comment by snoopyxz** [comment]
Ok, thanks for help have a good day.

**Comment by nixrajput** [comment]
I am working on the chat feature, after that I will make proper documentation for the APIs.

Because I am working alone on this whole project, this is why I couldn't make proper documentation.

**Comment by nixrajput** [comment]
Same to u

**Comment by snoopyxz** [comment]
sorry for bothering you with this but i'm new to this and i was curious about your project it's amazing keep up the good work if i could help i would but i don't know. (sorry bad english haha).

**Comment by nixrajput** [comment]
np for your English...hahaha

Drop a message on Instagram. 

I will tell you if any help will be required.

Thanks
